// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.dns.config.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class UpdatesGssapi {
    /**
     * @return This or &lt;span pulumi-lang-nodejs=&#34;`password`&#34; pulumi-lang-dotnet=&#34;`Password`&#34; pulumi-lang-go=&#34;`password`&#34; pulumi-lang-python=&#34;`password`&#34; pulumi-lang-yaml=&#34;`password`&#34; pulumi-lang-java=&#34;`password`&#34; pulumi-lang-hcl=&#34;`password`&#34;&gt;`password`&lt;/span&gt; is required if &lt;span pulumi-lang-nodejs=&#34;`username`&#34; pulumi-lang-dotnet=&#34;`Username`&#34; pulumi-lang-go=&#34;`username`&#34; pulumi-lang-python=&#34;`username`&#34; pulumi-lang-yaml=&#34;`username`&#34; pulumi-lang-java=&#34;`username`&#34; pulumi-lang-hcl=&#34;`username`&#34;&gt;`username`&lt;/span&gt; is set, not supported on Windows. The path to a keytab file containing a key for &lt;span pulumi-lang-nodejs=&#34;`username`&#34; pulumi-lang-dotnet=&#34;`Username`&#34; pulumi-lang-go=&#34;`username`&#34; pulumi-lang-python=&#34;`username`&#34; pulumi-lang-yaml=&#34;`username`&#34; pulumi-lang-java=&#34;`username`&#34; pulumi-lang-hcl=&#34;`username`&#34;&gt;`username`&lt;/span&gt;. Value can also be sourced from the DNS_UPDATE_KEYTAB environment variable.
     * 
     */
    private @Nullable String keytab;
    /**
     * @return This or &lt;span pulumi-lang-nodejs=&#34;`keytab`&#34; pulumi-lang-dotnet=&#34;`Keytab`&#34; pulumi-lang-go=&#34;`keytab`&#34; pulumi-lang-python=&#34;`keytab`&#34; pulumi-lang-yaml=&#34;`keytab`&#34; pulumi-lang-java=&#34;`keytab`&#34; pulumi-lang-hcl=&#34;`keytab`&#34;&gt;`keytab`&lt;/span&gt; is required if &lt;span pulumi-lang-nodejs=&#34;`username`&#34; pulumi-lang-dotnet=&#34;`Username`&#34; pulumi-lang-go=&#34;`username`&#34; pulumi-lang-python=&#34;`username`&#34; pulumi-lang-yaml=&#34;`username`&#34; pulumi-lang-java=&#34;`username`&#34; pulumi-lang-hcl=&#34;`username`&#34;&gt;`username`&lt;/span&gt; is set. The matching password for &lt;span pulumi-lang-nodejs=&#34;`username`&#34; pulumi-lang-dotnet=&#34;`Username`&#34; pulumi-lang-go=&#34;`username`&#34; pulumi-lang-python=&#34;`username`&#34; pulumi-lang-yaml=&#34;`username`&#34; pulumi-lang-java=&#34;`username`&#34; pulumi-lang-hcl=&#34;`username`&#34;&gt;`username`&lt;/span&gt;. Value can also be sourced from the DNS_UPDATE_PASSWORD environment variable.
     * 
     */
    private @Nullable String password;
    /**
     * @return The Kerberos realm or Active Directory domain. Value can also be sourced from the DNS_UPDATE_REALM environment variable.
     * 
     */
    private @Nullable String realm;
    /**
     * @return The name of the user to authenticate as. If not set the current user session will be used. Value can also be sourced from the DNS_UPDATE_USERNAME environment variable.
     * 
     */
    private @Nullable String username;

    private UpdatesGssapi() {}
    /**
     * @return This or &lt;span pulumi-lang-nodejs=&#34;`password`&#34; pulumi-lang-dotnet=&#34;`Password`&#34; pulumi-lang-go=&#34;`password`&#34; pulumi-lang-python=&#34;`password`&#34; pulumi-lang-yaml=&#34;`password`&#34; pulumi-lang-java=&#34;`password`&#34; pulumi-lang-hcl=&#34;`password`&#34;&gt;`password`&lt;/span&gt; is required if &lt;span pulumi-lang-nodejs=&#34;`username`&#34; pulumi-lang-dotnet=&#34;`Username`&#34; pulumi-lang-go=&#34;`username`&#34; pulumi-lang-python=&#34;`username`&#34; pulumi-lang-yaml=&#34;`username`&#34; pulumi-lang-java=&#34;`username`&#34; pulumi-lang-hcl=&#34;`username`&#34;&gt;`username`&lt;/span&gt; is set, not supported on Windows. The path to a keytab file containing a key for &lt;span pulumi-lang-nodejs=&#34;`username`&#34; pulumi-lang-dotnet=&#34;`Username`&#34; pulumi-lang-go=&#34;`username`&#34; pulumi-lang-python=&#34;`username`&#34; pulumi-lang-yaml=&#34;`username`&#34; pulumi-lang-java=&#34;`username`&#34; pulumi-lang-hcl=&#34;`username`&#34;&gt;`username`&lt;/span&gt;. Value can also be sourced from the DNS_UPDATE_KEYTAB environment variable.
     * 
     */
    public Optional<String> keytab() {
        return Optional.ofNullable(this.keytab);
    }
    /**
     * @return This or &lt;span pulumi-lang-nodejs=&#34;`keytab`&#34; pulumi-lang-dotnet=&#34;`Keytab`&#34; pulumi-lang-go=&#34;`keytab`&#34; pulumi-lang-python=&#34;`keytab`&#34; pulumi-lang-yaml=&#34;`keytab`&#34; pulumi-lang-java=&#34;`keytab`&#34; pulumi-lang-hcl=&#34;`keytab`&#34;&gt;`keytab`&lt;/span&gt; is required if &lt;span pulumi-lang-nodejs=&#34;`username`&#34; pulumi-lang-dotnet=&#34;`Username`&#34; pulumi-lang-go=&#34;`username`&#34; pulumi-lang-python=&#34;`username`&#34; pulumi-lang-yaml=&#34;`username`&#34; pulumi-lang-java=&#34;`username`&#34; pulumi-lang-hcl=&#34;`username`&#34;&gt;`username`&lt;/span&gt; is set. The matching password for &lt;span pulumi-lang-nodejs=&#34;`username`&#34; pulumi-lang-dotnet=&#34;`Username`&#34; pulumi-lang-go=&#34;`username`&#34; pulumi-lang-python=&#34;`username`&#34; pulumi-lang-yaml=&#34;`username`&#34; pulumi-lang-java=&#34;`username`&#34; pulumi-lang-hcl=&#34;`username`&#34;&gt;`username`&lt;/span&gt;. Value can also be sourced from the DNS_UPDATE_PASSWORD environment variable.
     * 
     */
    public Optional<String> password() {
        return Optional.ofNullable(this.password);
    }
    /**
     * @return The Kerberos realm or Active Directory domain. Value can also be sourced from the DNS_UPDATE_REALM environment variable.
     * 
     */
    public Optional<String> realm() {
        return Optional.ofNullable(this.realm);
    }
    /**
     * @return The name of the user to authenticate as. If not set the current user session will be used. Value can also be sourced from the DNS_UPDATE_USERNAME environment variable.
     * 
     */
    public Optional<String> username() {
        return Optional.ofNullable(this.username);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(UpdatesGssapi defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String keytab;
        private @Nullable String password;
        private @Nullable String realm;
        private @Nullable String username;
        public Builder() {}
        public Builder(UpdatesGssapi defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.keytab = defaults.keytab;
    	      this.password = defaults.password;
    	      this.realm = defaults.realm;
    	      this.username = defaults.username;
        }

        @CustomType.Setter
        public Builder keytab(@Nullable String keytab) {

            this.keytab = keytab;
            return this;
        }
        @CustomType.Setter
        public Builder password(@Nullable String password) {

            this.password = password;
            return this;
        }
        @CustomType.Setter
        public Builder realm(@Nullable String realm) {

            this.realm = realm;
            return this;
        }
        @CustomType.Setter
        public Builder username(@Nullable String username) {

            this.username = username;
            return this;
        }
        public UpdatesGssapi build() {
            final var _resultValue = new UpdatesGssapi();
            _resultValue.keytab = keytab;
            _resultValue.password = password;
            _resultValue.realm = realm;
            _resultValue.username = username;
            return _resultValue;
        }
    }
}
