// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package myproject;

import com.pulumi.core.TypeShape;
import com.pulumi.core.internal.Codegen;
import com.pulumi.dns.config.inputs.Updates;
import java.util.List;
import java.util.Optional;

public final class Config {

    private static final com.pulumi.Config config = com.pulumi.Config.of("dns");
/**
 * When the provider is used for DNS updates, this block is required. Only one &lt;span pulumi-lang-nodejs=&#34;`update`&#34; pulumi-lang-dotnet=&#34;`Update`&#34; pulumi-lang-go=&#34;`update`&#34; pulumi-lang-python=&#34;`update`&#34; pulumi-lang-yaml=&#34;`update`&#34; pulumi-lang-java=&#34;`update`&#34; pulumi-lang-hcl=&#34;`update`&#34;&gt;`update`&lt;/span&gt; block may be in the configuration.
 * 
 */
    public Optional<List<Updates>> updates() {
        return Codegen.objectProp("updates", TypeShape.<List<Updates>>builder(List.class).addParameter(Updates.class).build()).config(config).get();
    }
}
