// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.dns;

import com.pulumi.core.Output;
import com.pulumi.core.TypeShape;
import com.pulumi.deployment.Deployment;
import com.pulumi.deployment.InvokeOptions;
import com.pulumi.deployment.InvokeOutputOptions;
import com.pulumi.dns.Utilities;
import com.pulumi.dns.inputs.GetARecordSetArgs;
import com.pulumi.dns.inputs.GetARecordSetPlainArgs;
import com.pulumi.dns.inputs.GetAaaaRecordSetArgs;
import com.pulumi.dns.inputs.GetAaaaRecordSetPlainArgs;
import com.pulumi.dns.inputs.GetCnameRecordSetArgs;
import com.pulumi.dns.inputs.GetCnameRecordSetPlainArgs;
import com.pulumi.dns.inputs.GetMxRecordSetArgs;
import com.pulumi.dns.inputs.GetMxRecordSetPlainArgs;
import com.pulumi.dns.inputs.GetNsRecordSetArgs;
import com.pulumi.dns.inputs.GetNsRecordSetPlainArgs;
import com.pulumi.dns.inputs.GetPtrRecordSetArgs;
import com.pulumi.dns.inputs.GetPtrRecordSetPlainArgs;
import com.pulumi.dns.inputs.GetSrvRecordSetArgs;
import com.pulumi.dns.inputs.GetSrvRecordSetPlainArgs;
import com.pulumi.dns.inputs.GetTxtRecordSetArgs;
import com.pulumi.dns.inputs.GetTxtRecordSetPlainArgs;
import com.pulumi.dns.outputs.GetARecordSetResult;
import com.pulumi.dns.outputs.GetAaaaRecordSetResult;
import com.pulumi.dns.outputs.GetCnameRecordSetResult;
import com.pulumi.dns.outputs.GetMxRecordSetResult;
import com.pulumi.dns.outputs.GetNsRecordSetResult;
import com.pulumi.dns.outputs.GetPtrRecordSetResult;
import com.pulumi.dns.outputs.GetSrvRecordSetResult;
import com.pulumi.dns.outputs.GetTxtRecordSetResult;
import java.util.concurrent.CompletableFuture;

public final class DnsFunctions {
    public static Output<GetARecordSetResult> getARecordSet(GetARecordSetArgs args) {
        return getARecordSet(args, InvokeOptions.Empty);
    }
    public static CompletableFuture<GetARecordSetResult> getARecordSetPlain(GetARecordSetPlainArgs args) {
        return getARecordSetPlain(args, InvokeOptions.Empty);
    }
    public static Output<GetARecordSetResult> getARecordSet(GetARecordSetArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("dns:index/getARecordSet:getARecordSet", TypeShape.of(GetARecordSetResult.class), args, Utilities.withVersion(options), Utilities.getPackageRef());
    }
    public static Output<GetARecordSetResult> getARecordSet(GetARecordSetArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("dns:index/getARecordSet:getARecordSet", TypeShape.of(GetARecordSetResult.class), args, Utilities.withVersion(options), Utilities.getPackageRef());
    }
    public static CompletableFuture<GetARecordSetResult> getARecordSetPlain(GetARecordSetPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("dns:index/getARecordSet:getARecordSet", TypeShape.of(GetARecordSetResult.class), args, Utilities.withVersion(options), Utilities.getPackageRef());
    }
    public static Output<GetAaaaRecordSetResult> getAaaaRecordSet(GetAaaaRecordSetArgs args) {
        return getAaaaRecordSet(args, InvokeOptions.Empty);
    }
    public static CompletableFuture<GetAaaaRecordSetResult> getAaaaRecordSetPlain(GetAaaaRecordSetPlainArgs args) {
        return getAaaaRecordSetPlain(args, InvokeOptions.Empty);
    }
    public static Output<GetAaaaRecordSetResult> getAaaaRecordSet(GetAaaaRecordSetArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("dns:index/getAaaaRecordSet:getAaaaRecordSet", TypeShape.of(GetAaaaRecordSetResult.class), args, Utilities.withVersion(options), Utilities.getPackageRef());
    }
    public static Output<GetAaaaRecordSetResult> getAaaaRecordSet(GetAaaaRecordSetArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("dns:index/getAaaaRecordSet:getAaaaRecordSet", TypeShape.of(GetAaaaRecordSetResult.class), args, Utilities.withVersion(options), Utilities.getPackageRef());
    }
    public static CompletableFuture<GetAaaaRecordSetResult> getAaaaRecordSetPlain(GetAaaaRecordSetPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("dns:index/getAaaaRecordSet:getAaaaRecordSet", TypeShape.of(GetAaaaRecordSetResult.class), args, Utilities.withVersion(options), Utilities.getPackageRef());
    }
    public static Output<GetCnameRecordSetResult> getCnameRecordSet(GetCnameRecordSetArgs args) {
        return getCnameRecordSet(args, InvokeOptions.Empty);
    }
    public static CompletableFuture<GetCnameRecordSetResult> getCnameRecordSetPlain(GetCnameRecordSetPlainArgs args) {
        return getCnameRecordSetPlain(args, InvokeOptions.Empty);
    }
    public static Output<GetCnameRecordSetResult> getCnameRecordSet(GetCnameRecordSetArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("dns:index/getCnameRecordSet:getCnameRecordSet", TypeShape.of(GetCnameRecordSetResult.class), args, Utilities.withVersion(options), Utilities.getPackageRef());
    }
    public static Output<GetCnameRecordSetResult> getCnameRecordSet(GetCnameRecordSetArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("dns:index/getCnameRecordSet:getCnameRecordSet", TypeShape.of(GetCnameRecordSetResult.class), args, Utilities.withVersion(options), Utilities.getPackageRef());
    }
    public static CompletableFuture<GetCnameRecordSetResult> getCnameRecordSetPlain(GetCnameRecordSetPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("dns:index/getCnameRecordSet:getCnameRecordSet", TypeShape.of(GetCnameRecordSetResult.class), args, Utilities.withVersion(options), Utilities.getPackageRef());
    }
    public static Output<GetMxRecordSetResult> getMxRecordSet(GetMxRecordSetArgs args) {
        return getMxRecordSet(args, InvokeOptions.Empty);
    }
    public static CompletableFuture<GetMxRecordSetResult> getMxRecordSetPlain(GetMxRecordSetPlainArgs args) {
        return getMxRecordSetPlain(args, InvokeOptions.Empty);
    }
    public static Output<GetMxRecordSetResult> getMxRecordSet(GetMxRecordSetArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("dns:index/getMxRecordSet:getMxRecordSet", TypeShape.of(GetMxRecordSetResult.class), args, Utilities.withVersion(options), Utilities.getPackageRef());
    }
    public static Output<GetMxRecordSetResult> getMxRecordSet(GetMxRecordSetArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("dns:index/getMxRecordSet:getMxRecordSet", TypeShape.of(GetMxRecordSetResult.class), args, Utilities.withVersion(options), Utilities.getPackageRef());
    }
    public static CompletableFuture<GetMxRecordSetResult> getMxRecordSetPlain(GetMxRecordSetPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("dns:index/getMxRecordSet:getMxRecordSet", TypeShape.of(GetMxRecordSetResult.class), args, Utilities.withVersion(options), Utilities.getPackageRef());
    }
    public static Output<GetNsRecordSetResult> getNsRecordSet(GetNsRecordSetArgs args) {
        return getNsRecordSet(args, InvokeOptions.Empty);
    }
    public static CompletableFuture<GetNsRecordSetResult> getNsRecordSetPlain(GetNsRecordSetPlainArgs args) {
        return getNsRecordSetPlain(args, InvokeOptions.Empty);
    }
    public static Output<GetNsRecordSetResult> getNsRecordSet(GetNsRecordSetArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("dns:index/getNsRecordSet:getNsRecordSet", TypeShape.of(GetNsRecordSetResult.class), args, Utilities.withVersion(options), Utilities.getPackageRef());
    }
    public static Output<GetNsRecordSetResult> getNsRecordSet(GetNsRecordSetArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("dns:index/getNsRecordSet:getNsRecordSet", TypeShape.of(GetNsRecordSetResult.class), args, Utilities.withVersion(options), Utilities.getPackageRef());
    }
    public static CompletableFuture<GetNsRecordSetResult> getNsRecordSetPlain(GetNsRecordSetPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("dns:index/getNsRecordSet:getNsRecordSet", TypeShape.of(GetNsRecordSetResult.class), args, Utilities.withVersion(options), Utilities.getPackageRef());
    }
    public static Output<GetPtrRecordSetResult> getPtrRecordSet(GetPtrRecordSetArgs args) {
        return getPtrRecordSet(args, InvokeOptions.Empty);
    }
    public static CompletableFuture<GetPtrRecordSetResult> getPtrRecordSetPlain(GetPtrRecordSetPlainArgs args) {
        return getPtrRecordSetPlain(args, InvokeOptions.Empty);
    }
    public static Output<GetPtrRecordSetResult> getPtrRecordSet(GetPtrRecordSetArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("dns:index/getPtrRecordSet:getPtrRecordSet", TypeShape.of(GetPtrRecordSetResult.class), args, Utilities.withVersion(options), Utilities.getPackageRef());
    }
    public static Output<GetPtrRecordSetResult> getPtrRecordSet(GetPtrRecordSetArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("dns:index/getPtrRecordSet:getPtrRecordSet", TypeShape.of(GetPtrRecordSetResult.class), args, Utilities.withVersion(options), Utilities.getPackageRef());
    }
    public static CompletableFuture<GetPtrRecordSetResult> getPtrRecordSetPlain(GetPtrRecordSetPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("dns:index/getPtrRecordSet:getPtrRecordSet", TypeShape.of(GetPtrRecordSetResult.class), args, Utilities.withVersion(options), Utilities.getPackageRef());
    }
    public static Output<GetSrvRecordSetResult> getSrvRecordSet(GetSrvRecordSetArgs args) {
        return getSrvRecordSet(args, InvokeOptions.Empty);
    }
    public static CompletableFuture<GetSrvRecordSetResult> getSrvRecordSetPlain(GetSrvRecordSetPlainArgs args) {
        return getSrvRecordSetPlain(args, InvokeOptions.Empty);
    }
    public static Output<GetSrvRecordSetResult> getSrvRecordSet(GetSrvRecordSetArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("dns:index/getSrvRecordSet:getSrvRecordSet", TypeShape.of(GetSrvRecordSetResult.class), args, Utilities.withVersion(options), Utilities.getPackageRef());
    }
    public static Output<GetSrvRecordSetResult> getSrvRecordSet(GetSrvRecordSetArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("dns:index/getSrvRecordSet:getSrvRecordSet", TypeShape.of(GetSrvRecordSetResult.class), args, Utilities.withVersion(options), Utilities.getPackageRef());
    }
    public static CompletableFuture<GetSrvRecordSetResult> getSrvRecordSetPlain(GetSrvRecordSetPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("dns:index/getSrvRecordSet:getSrvRecordSet", TypeShape.of(GetSrvRecordSetResult.class), args, Utilities.withVersion(options), Utilities.getPackageRef());
    }
    public static Output<GetTxtRecordSetResult> getTxtRecordSet(GetTxtRecordSetArgs args) {
        return getTxtRecordSet(args, InvokeOptions.Empty);
    }
    public static CompletableFuture<GetTxtRecordSetResult> getTxtRecordSetPlain(GetTxtRecordSetPlainArgs args) {
        return getTxtRecordSetPlain(args, InvokeOptions.Empty);
    }
    public static Output<GetTxtRecordSetResult> getTxtRecordSet(GetTxtRecordSetArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("dns:index/getTxtRecordSet:getTxtRecordSet", TypeShape.of(GetTxtRecordSetResult.class), args, Utilities.withVersion(options), Utilities.getPackageRef());
    }
    public static Output<GetTxtRecordSetResult> getTxtRecordSet(GetTxtRecordSetArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("dns:index/getTxtRecordSet:getTxtRecordSet", TypeShape.of(GetTxtRecordSetResult.class), args, Utilities.withVersion(options), Utilities.getPackageRef());
    }
    public static CompletableFuture<GetTxtRecordSetResult> getTxtRecordSetPlain(GetTxtRecordSetPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("dns:index/getTxtRecordSet:getTxtRecordSet", TypeShape.of(GetTxtRecordSetResult.class), args, Utilities.withVersion(options), Utilities.getPackageRef());
    }
}
