// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.dns;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Double;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class NsRecordSetArgs extends com.pulumi.resources.ResourceArgs {

    public static final NsRecordSetArgs Empty = new NsRecordSetArgs();

    /**
     * The name of the record set. The &lt;span pulumi-lang-nodejs=&#34;`zone`&#34; pulumi-lang-dotnet=&#34;`Zone`&#34; pulumi-lang-go=&#34;`zone`&#34; pulumi-lang-python=&#34;`zone`&#34; pulumi-lang-yaml=&#34;`zone`&#34; pulumi-lang-java=&#34;`zone`&#34; pulumi-lang-hcl=&#34;`zone`&#34;&gt;`zone`&lt;/span&gt; argument will be appended to this value to create the full record path.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return The name of the record set. The &lt;span pulumi-lang-nodejs=&#34;`zone`&#34; pulumi-lang-dotnet=&#34;`Zone`&#34; pulumi-lang-go=&#34;`zone`&#34; pulumi-lang-python=&#34;`zone`&#34; pulumi-lang-yaml=&#34;`zone`&#34; pulumi-lang-java=&#34;`zone`&#34; pulumi-lang-hcl=&#34;`zone`&#34;&gt;`zone`&lt;/span&gt; argument will be appended to this value to create the full record path.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * The nameservers this record set will point to.
     * 
     */
    @Import(name="nameservers", required=true)
    private Output<List<String>> nameservers;

    /**
     * @return The nameservers this record set will point to.
     * 
     */
    public Output<List<String>> nameservers() {
        return this.nameservers;
    }

    /**
     * The TTL of the record set. Defaults to &lt;span pulumi-lang-nodejs=&#34;`3600`&#34; pulumi-lang-dotnet=&#34;`3600`&#34; pulumi-lang-go=&#34;`3600`&#34; pulumi-lang-python=&#34;`3600`&#34; pulumi-lang-yaml=&#34;`3600`&#34; pulumi-lang-java=&#34;`3600`&#34; pulumi-lang-hcl=&#34;`3600`&#34;&gt;`3600`&lt;/span&gt;.
     * 
     */
    @Import(name="ttl")
    private @Nullable Output<Double> ttl;

    /**
     * @return The TTL of the record set. Defaults to &lt;span pulumi-lang-nodejs=&#34;`3600`&#34; pulumi-lang-dotnet=&#34;`3600`&#34; pulumi-lang-go=&#34;`3600`&#34; pulumi-lang-python=&#34;`3600`&#34; pulumi-lang-yaml=&#34;`3600`&#34; pulumi-lang-java=&#34;`3600`&#34; pulumi-lang-hcl=&#34;`3600`&#34;&gt;`3600`&lt;/span&gt;.
     * 
     */
    public Optional<Output<Double>> ttl() {
        return Optional.ofNullable(this.ttl);
    }

    /**
     * DNS zone the record set belongs to. It must be an FQDN, that is, include the trailing dot.
     * 
     */
    @Import(name="zone", required=true)
    private Output<String> zone;

    /**
     * @return DNS zone the record set belongs to. It must be an FQDN, that is, include the trailing dot.
     * 
     */
    public Output<String> zone() {
        return this.zone;
    }

    private NsRecordSetArgs() {}

    private NsRecordSetArgs(NsRecordSetArgs $) {
        this.name = $.name;
        this.nameservers = $.nameservers;
        this.ttl = $.ttl;
        this.zone = $.zone;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(NsRecordSetArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private NsRecordSetArgs $;

        public Builder() {
            $ = new NsRecordSetArgs();
        }

        public Builder(NsRecordSetArgs defaults) {
            $ = new NsRecordSetArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param name The name of the record set. The &lt;span pulumi-lang-nodejs=&#34;`zone`&#34; pulumi-lang-dotnet=&#34;`Zone`&#34; pulumi-lang-go=&#34;`zone`&#34; pulumi-lang-python=&#34;`zone`&#34; pulumi-lang-yaml=&#34;`zone`&#34; pulumi-lang-java=&#34;`zone`&#34; pulumi-lang-hcl=&#34;`zone`&#34;&gt;`zone`&lt;/span&gt; argument will be appended to this value to create the full record path.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name The name of the record set. The &lt;span pulumi-lang-nodejs=&#34;`zone`&#34; pulumi-lang-dotnet=&#34;`Zone`&#34; pulumi-lang-go=&#34;`zone`&#34; pulumi-lang-python=&#34;`zone`&#34; pulumi-lang-yaml=&#34;`zone`&#34; pulumi-lang-java=&#34;`zone`&#34; pulumi-lang-hcl=&#34;`zone`&#34;&gt;`zone`&lt;/span&gt; argument will be appended to this value to create the full record path.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param nameservers The nameservers this record set will point to.
         * 
         * @return builder
         * 
         */
        public Builder nameservers(Output<List<String>> nameservers) {
            $.nameservers = nameservers;
            return this;
        }

        /**
         * @param nameservers The nameservers this record set will point to.
         * 
         * @return builder
         * 
         */
        public Builder nameservers(List<String> nameservers) {
            return nameservers(Output.of(nameservers));
        }

        /**
         * @param nameservers The nameservers this record set will point to.
         * 
         * @return builder
         * 
         */
        public Builder nameservers(String... nameservers) {
            return nameservers(List.of(nameservers));
        }

        /**
         * @param ttl The TTL of the record set. Defaults to &lt;span pulumi-lang-nodejs=&#34;`3600`&#34; pulumi-lang-dotnet=&#34;`3600`&#34; pulumi-lang-go=&#34;`3600`&#34; pulumi-lang-python=&#34;`3600`&#34; pulumi-lang-yaml=&#34;`3600`&#34; pulumi-lang-java=&#34;`3600`&#34; pulumi-lang-hcl=&#34;`3600`&#34;&gt;`3600`&lt;/span&gt;.
         * 
         * @return builder
         * 
         */
        public Builder ttl(@Nullable Output<Double> ttl) {
            $.ttl = ttl;
            return this;
        }

        /**
         * @param ttl The TTL of the record set. Defaults to &lt;span pulumi-lang-nodejs=&#34;`3600`&#34; pulumi-lang-dotnet=&#34;`3600`&#34; pulumi-lang-go=&#34;`3600`&#34; pulumi-lang-python=&#34;`3600`&#34; pulumi-lang-yaml=&#34;`3600`&#34; pulumi-lang-java=&#34;`3600`&#34; pulumi-lang-hcl=&#34;`3600`&#34;&gt;`3600`&lt;/span&gt;.
         * 
         * @return builder
         * 
         */
        public Builder ttl(Double ttl) {
            return ttl(Output.of(ttl));
        }

        /**
         * @param zone DNS zone the record set belongs to. It must be an FQDN, that is, include the trailing dot.
         * 
         * @return builder
         * 
         */
        public Builder zone(Output<String> zone) {
            $.zone = zone;
            return this;
        }

        /**
         * @param zone DNS zone the record set belongs to. It must be an FQDN, that is, include the trailing dot.
         * 
         * @return builder
         * 
         */
        public Builder zone(String zone) {
            return zone(Output.of(zone));
        }

        public NsRecordSetArgs build() {
            if ($.nameservers == null) {
                throw new MissingRequiredPropertyException("NsRecordSetArgs", "nameservers");
            }
            if ($.zone == null) {
                throw new MissingRequiredPropertyException("NsRecordSetArgs", "zone");
            }
            return $;
        }
    }

}
