// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.dns;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.dns.inputs.ProviderUpdateArgs;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ProviderArgs extends com.pulumi.resources.ResourceArgs {

    public static final ProviderArgs Empty = new ProviderArgs();

    /**
     * When the provider is used for DNS updates, this block is required. Only one &lt;span pulumi-lang-nodejs=&#34;`update`&#34; pulumi-lang-dotnet=&#34;`Update`&#34; pulumi-lang-go=&#34;`update`&#34; pulumi-lang-python=&#34;`update`&#34; pulumi-lang-yaml=&#34;`update`&#34; pulumi-lang-java=&#34;`update`&#34; pulumi-lang-hcl=&#34;`update`&#34;&gt;`update`&lt;/span&gt; block may be in the configuration.
     * 
     */
    @Import(name="updates", json=true)
    private @Nullable Output<List<ProviderUpdateArgs>> updates;

    /**
     * @return When the provider is used for DNS updates, this block is required. Only one &lt;span pulumi-lang-nodejs=&#34;`update`&#34; pulumi-lang-dotnet=&#34;`Update`&#34; pulumi-lang-go=&#34;`update`&#34; pulumi-lang-python=&#34;`update`&#34; pulumi-lang-yaml=&#34;`update`&#34; pulumi-lang-java=&#34;`update`&#34; pulumi-lang-hcl=&#34;`update`&#34;&gt;`update`&lt;/span&gt; block may be in the configuration.
     * 
     */
    public Optional<Output<List<ProviderUpdateArgs>>> updates() {
        return Optional.ofNullable(this.updates);
    }

    private ProviderArgs() {}

    private ProviderArgs(ProviderArgs $) {
        this.updates = $.updates;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ProviderArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ProviderArgs $;

        public Builder() {
            $ = new ProviderArgs();
        }

        public Builder(ProviderArgs defaults) {
            $ = new ProviderArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param updates When the provider is used for DNS updates, this block is required. Only one &lt;span pulumi-lang-nodejs=&#34;`update`&#34; pulumi-lang-dotnet=&#34;`Update`&#34; pulumi-lang-go=&#34;`update`&#34; pulumi-lang-python=&#34;`update`&#34; pulumi-lang-yaml=&#34;`update`&#34; pulumi-lang-java=&#34;`update`&#34; pulumi-lang-hcl=&#34;`update`&#34;&gt;`update`&lt;/span&gt; block may be in the configuration.
         * 
         * @return builder
         * 
         */
        public Builder updates(@Nullable Output<List<ProviderUpdateArgs>> updates) {
            $.updates = updates;
            return this;
        }

        /**
         * @param updates When the provider is used for DNS updates, this block is required. Only one &lt;span pulumi-lang-nodejs=&#34;`update`&#34; pulumi-lang-dotnet=&#34;`Update`&#34; pulumi-lang-go=&#34;`update`&#34; pulumi-lang-python=&#34;`update`&#34; pulumi-lang-yaml=&#34;`update`&#34; pulumi-lang-java=&#34;`update`&#34; pulumi-lang-hcl=&#34;`update`&#34;&gt;`update`&lt;/span&gt; block may be in the configuration.
         * 
         * @return builder
         * 
         */
        public Builder updates(List<ProviderUpdateArgs> updates) {
            return updates(Output.of(updates));
        }

        /**
         * @param updates When the provider is used for DNS updates, this block is required. Only one &lt;span pulumi-lang-nodejs=&#34;`update`&#34; pulumi-lang-dotnet=&#34;`Update`&#34; pulumi-lang-go=&#34;`update`&#34; pulumi-lang-python=&#34;`update`&#34; pulumi-lang-yaml=&#34;`update`&#34; pulumi-lang-java=&#34;`update`&#34; pulumi-lang-hcl=&#34;`update`&#34;&gt;`update`&lt;/span&gt; block may be in the configuration.
         * 
         * @return builder
         * 
         */
        public Builder updates(ProviderUpdateArgs... updates) {
            return updates(List.of(updates));
        }

        public ProviderArgs build() {
            return $;
        }
    }

}
