// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.dns;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.dns.SrvRecordSetArgs;
import com.pulumi.dns.Utilities;
import com.pulumi.dns.inputs.SrvRecordSetState;
import com.pulumi.dns.outputs.SrvRecordSetSrv;
import java.lang.Double;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

@ResourceType(type="dns:index/srvRecordSet:SrvRecordSet")
public class SrvRecordSet extends com.pulumi.resources.CustomResource {
    /**
     * The name of the record set. The &lt;span pulumi-lang-nodejs=&#34;`zone`&#34; pulumi-lang-dotnet=&#34;`Zone`&#34; pulumi-lang-go=&#34;`zone`&#34; pulumi-lang-python=&#34;`zone`&#34; pulumi-lang-yaml=&#34;`zone`&#34; pulumi-lang-java=&#34;`zone`&#34; pulumi-lang-hcl=&#34;`zone`&#34;&gt;`zone`&lt;/span&gt; argument will be appended to this value to create the full record path.
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return The name of the record set. The &lt;span pulumi-lang-nodejs=&#34;`zone`&#34; pulumi-lang-dotnet=&#34;`Zone`&#34; pulumi-lang-go=&#34;`zone`&#34; pulumi-lang-python=&#34;`zone`&#34; pulumi-lang-yaml=&#34;`zone`&#34; pulumi-lang-java=&#34;`zone`&#34; pulumi-lang-hcl=&#34;`zone`&#34;&gt;`zone`&lt;/span&gt; argument will be appended to this value to create the full record path.
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * Can be specified multiple times for each SRV record.
     * 
     */
    @Export(name="srvs", refs={List.class,SrvRecordSetSrv.class}, tree="[0,1]")
    private Output</* @Nullable */ List<SrvRecordSetSrv>> srvs;

    /**
     * @return Can be specified multiple times for each SRV record.
     * 
     */
    public Output<Optional<List<SrvRecordSetSrv>>> srvs() {
        return Codegen.optional(this.srvs);
    }
    /**
     * The TTL of the record set. Defaults to &lt;span pulumi-lang-nodejs=&#34;`3600`&#34; pulumi-lang-dotnet=&#34;`3600`&#34; pulumi-lang-go=&#34;`3600`&#34; pulumi-lang-python=&#34;`3600`&#34; pulumi-lang-yaml=&#34;`3600`&#34; pulumi-lang-java=&#34;`3600`&#34; pulumi-lang-hcl=&#34;`3600`&#34;&gt;`3600`&lt;/span&gt;.
     * 
     */
    @Export(name="ttl", refs={Double.class}, tree="[0]")
    private Output<Double> ttl;

    /**
     * @return The TTL of the record set. Defaults to &lt;span pulumi-lang-nodejs=&#34;`3600`&#34; pulumi-lang-dotnet=&#34;`3600`&#34; pulumi-lang-go=&#34;`3600`&#34; pulumi-lang-python=&#34;`3600`&#34; pulumi-lang-yaml=&#34;`3600`&#34; pulumi-lang-java=&#34;`3600`&#34; pulumi-lang-hcl=&#34;`3600`&#34;&gt;`3600`&lt;/span&gt;.
     * 
     */
    public Output<Double> ttl() {
        return this.ttl;
    }
    /**
     * DNS zone the record set belongs to. It must be an FQDN, that is, include the trailing dot.
     * 
     */
    @Export(name="zone", refs={String.class}, tree="[0]")
    private Output<String> zone;

    /**
     * @return DNS zone the record set belongs to. It must be an FQDN, that is, include the trailing dot.
     * 
     */
    public Output<String> zone() {
        return this.zone;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public SrvRecordSet(java.lang.String name) {
        this(name, SrvRecordSetArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public SrvRecordSet(java.lang.String name, SrvRecordSetArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public SrvRecordSet(java.lang.String name, SrvRecordSetArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("dns:index/srvRecordSet:SrvRecordSet", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false, Utilities.getPackageRef());
    }

    private SrvRecordSet(java.lang.String name, Output<java.lang.String> id, @Nullable SrvRecordSetState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("dns:index/srvRecordSet:SrvRecordSet", name, state, makeResourceOptions(options, id), false, Utilities.getPackageRef());
    }

    private static SrvRecordSetArgs makeArgs(SrvRecordSetArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? SrvRecordSetArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static SrvRecordSet get(java.lang.String name, Output<java.lang.String> id, @Nullable SrvRecordSetState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new SrvRecordSet(name, id, state, options);
    }
}
