// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.dns.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetAaaaRecordSetResult {
    private List<String> addrs;
    private String host;
    private String id;

    private GetAaaaRecordSetResult() {}
    public List<String> addrs() {
        return this.addrs;
    }
    public String host() {
        return this.host;
    }
    public String id() {
        return this.id;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetAaaaRecordSetResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private List<String> addrs;
        private String host;
        private String id;
        public Builder() {}
        public Builder(GetAaaaRecordSetResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.addrs = defaults.addrs;
    	      this.host = defaults.host;
    	      this.id = defaults.id;
        }

        @CustomType.Setter
        public Builder addrs(List<String> addrs) {
            if (addrs == null) {
              throw new MissingRequiredPropertyException("GetAaaaRecordSetResult", "addrs");
            }
            this.addrs = addrs;
            return this;
        }
        public Builder addrs(String... addrs) {
            return addrs(List.of(addrs));
        }
        @CustomType.Setter
        public Builder host(String host) {
            if (host == null) {
              throw new MissingRequiredPropertyException("GetAaaaRecordSetResult", "host");
            }
            this.host = host;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetAaaaRecordSetResult", "id");
            }
            this.id = id;
            return this;
        }
        public GetAaaaRecordSetResult build() {
            final var _resultValue = new GetAaaaRecordSetResult();
            _resultValue.addrs = addrs;
            _resultValue.host = host;
            _resultValue.id = id;
            return _resultValue;
        }
    }
}
