// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.dns.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetCnameRecordSetResult {
    private String cname;
    private String host;
    private String id;

    private GetCnameRecordSetResult() {}
    public String cname() {
        return this.cname;
    }
    public String host() {
        return this.host;
    }
    public String id() {
        return this.id;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetCnameRecordSetResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String cname;
        private String host;
        private String id;
        public Builder() {}
        public Builder(GetCnameRecordSetResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.cname = defaults.cname;
    	      this.host = defaults.host;
    	      this.id = defaults.id;
        }

        @CustomType.Setter
        public Builder cname(String cname) {
            if (cname == null) {
              throw new MissingRequiredPropertyException("GetCnameRecordSetResult", "cname");
            }
            this.cname = cname;
            return this;
        }
        @CustomType.Setter
        public Builder host(String host) {
            if (host == null) {
              throw new MissingRequiredPropertyException("GetCnameRecordSetResult", "host");
            }
            this.host = host;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetCnameRecordSetResult", "id");
            }
            this.id = id;
            return this;
        }
        public GetCnameRecordSetResult build() {
            final var _resultValue = new GetCnameRecordSetResult();
            _resultValue.cname = cname;
            _resultValue.host = host;
            _resultValue.id = id;
            return _resultValue;
        }
    }
}
