// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.dns.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Double;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetMxRecordSetMx {
    private @Nullable String exchange;
    private @Nullable Double preference;

    private GetMxRecordSetMx() {}
    public Optional<String> exchange() {
        return Optional.ofNullable(this.exchange);
    }
    public Optional<Double> preference() {
        return Optional.ofNullable(this.preference);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetMxRecordSetMx defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String exchange;
        private @Nullable Double preference;
        public Builder() {}
        public Builder(GetMxRecordSetMx defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.exchange = defaults.exchange;
    	      this.preference = defaults.preference;
        }

        @CustomType.Setter
        public Builder exchange(@Nullable String exchange) {

            this.exchange = exchange;
            return this;
        }
        @CustomType.Setter
        public Builder preference(@Nullable Double preference) {

            this.preference = preference;
            return this;
        }
        public GetMxRecordSetMx build() {
            final var _resultValue = new GetMxRecordSetMx();
            _resultValue.exchange = exchange;
            _resultValue.preference = preference;
            return _resultValue;
        }
    }
}
