// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.dns.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.dns.outputs.GetMxRecordSetMx;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetMxRecordSetResult {
    private String domain;
    private String id;
    private List<GetMxRecordSetMx> mxes;

    private GetMxRecordSetResult() {}
    public String domain() {
        return this.domain;
    }
    public String id() {
        return this.id;
    }
    public List<GetMxRecordSetMx> mxes() {
        return this.mxes;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetMxRecordSetResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String domain;
        private String id;
        private List<GetMxRecordSetMx> mxes;
        public Builder() {}
        public Builder(GetMxRecordSetResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.domain = defaults.domain;
    	      this.id = defaults.id;
    	      this.mxes = defaults.mxes;
        }

        @CustomType.Setter
        public Builder domain(String domain) {
            if (domain == null) {
              throw new MissingRequiredPropertyException("GetMxRecordSetResult", "domain");
            }
            this.domain = domain;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetMxRecordSetResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder mxes(List<GetMxRecordSetMx> mxes) {
            if (mxes == null) {
              throw new MissingRequiredPropertyException("GetMxRecordSetResult", "mxes");
            }
            this.mxes = mxes;
            return this;
        }
        public Builder mxes(GetMxRecordSetMx... mxes) {
            return mxes(List.of(mxes));
        }
        public GetMxRecordSetResult build() {
            final var _resultValue = new GetMxRecordSetResult();
            _resultValue.domain = domain;
            _resultValue.id = id;
            _resultValue.mxes = mxes;
            return _resultValue;
        }
    }
}
