// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.dns.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetNsRecordSetResult {
    private String host;
    private String id;
    private List<String> nameservers;

    private GetNsRecordSetResult() {}
    public String host() {
        return this.host;
    }
    public String id() {
        return this.id;
    }
    public List<String> nameservers() {
        return this.nameservers;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetNsRecordSetResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String host;
        private String id;
        private List<String> nameservers;
        public Builder() {}
        public Builder(GetNsRecordSetResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.host = defaults.host;
    	      this.id = defaults.id;
    	      this.nameservers = defaults.nameservers;
        }

        @CustomType.Setter
        public Builder host(String host) {
            if (host == null) {
              throw new MissingRequiredPropertyException("GetNsRecordSetResult", "host");
            }
            this.host = host;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetNsRecordSetResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder nameservers(List<String> nameservers) {
            if (nameservers == null) {
              throw new MissingRequiredPropertyException("GetNsRecordSetResult", "nameservers");
            }
            this.nameservers = nameservers;
            return this;
        }
        public Builder nameservers(String... nameservers) {
            return nameservers(List.of(nameservers));
        }
        public GetNsRecordSetResult build() {
            final var _resultValue = new GetNsRecordSetResult();
            _resultValue.host = host;
            _resultValue.id = id;
            _resultValue.nameservers = nameservers;
            return _resultValue;
        }
    }
}
