// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.dns.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetPtrRecordSetResult {
    private String id;
    private String ipAddress;
    private String ptr;

    private GetPtrRecordSetResult() {}
    public String id() {
        return this.id;
    }
    public String ipAddress() {
        return this.ipAddress;
    }
    public String ptr() {
        return this.ptr;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetPtrRecordSetResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String id;
        private String ipAddress;
        private String ptr;
        public Builder() {}
        public Builder(GetPtrRecordSetResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.id = defaults.id;
    	      this.ipAddress = defaults.ipAddress;
    	      this.ptr = defaults.ptr;
        }

        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetPtrRecordSetResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder ipAddress(String ipAddress) {
            if (ipAddress == null) {
              throw new MissingRequiredPropertyException("GetPtrRecordSetResult", "ipAddress");
            }
            this.ipAddress = ipAddress;
            return this;
        }
        @CustomType.Setter
        public Builder ptr(String ptr) {
            if (ptr == null) {
              throw new MissingRequiredPropertyException("GetPtrRecordSetResult", "ptr");
            }
            this.ptr = ptr;
            return this;
        }
        public GetPtrRecordSetResult build() {
            final var _resultValue = new GetPtrRecordSetResult();
            _resultValue.id = id;
            _resultValue.ipAddress = ipAddress;
            _resultValue.ptr = ptr;
            return _resultValue;
        }
    }
}
