// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.dns.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.dns.outputs.GetSrvRecordSetSrv;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetSrvRecordSetResult {
    private String id;
    private String service;
    private List<GetSrvRecordSetSrv> srvs;

    private GetSrvRecordSetResult() {}
    public String id() {
        return this.id;
    }
    public String service() {
        return this.service;
    }
    public List<GetSrvRecordSetSrv> srvs() {
        return this.srvs;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetSrvRecordSetResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String id;
        private String service;
        private List<GetSrvRecordSetSrv> srvs;
        public Builder() {}
        public Builder(GetSrvRecordSetResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.id = defaults.id;
    	      this.service = defaults.service;
    	      this.srvs = defaults.srvs;
        }

        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetSrvRecordSetResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder service(String service) {
            if (service == null) {
              throw new MissingRequiredPropertyException("GetSrvRecordSetResult", "service");
            }
            this.service = service;
            return this;
        }
        @CustomType.Setter
        public Builder srvs(List<GetSrvRecordSetSrv> srvs) {
            if (srvs == null) {
              throw new MissingRequiredPropertyException("GetSrvRecordSetResult", "srvs");
            }
            this.srvs = srvs;
            return this;
        }
        public Builder srvs(GetSrvRecordSetSrv... srvs) {
            return srvs(List.of(srvs));
        }
        public GetSrvRecordSetResult build() {
            final var _resultValue = new GetSrvRecordSetResult();
            _resultValue.id = id;
            _resultValue.service = service;
            _resultValue.srvs = srvs;
            return _resultValue;
        }
    }
}
