// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.dns.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Double;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetSrvRecordSetSrv {
    private @Nullable Double port;
    private @Nullable Double priority;
    private @Nullable String target;
    private @Nullable Double weight;

    private GetSrvRecordSetSrv() {}
    public Optional<Double> port() {
        return Optional.ofNullable(this.port);
    }
    public Optional<Double> priority() {
        return Optional.ofNullable(this.priority);
    }
    public Optional<String> target() {
        return Optional.ofNullable(this.target);
    }
    public Optional<Double> weight() {
        return Optional.ofNullable(this.weight);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetSrvRecordSetSrv defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable Double port;
        private @Nullable Double priority;
        private @Nullable String target;
        private @Nullable Double weight;
        public Builder() {}
        public Builder(GetSrvRecordSetSrv defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.port = defaults.port;
    	      this.priority = defaults.priority;
    	      this.target = defaults.target;
    	      this.weight = defaults.weight;
        }

        @CustomType.Setter
        public Builder port(@Nullable Double port) {

            this.port = port;
            return this;
        }
        @CustomType.Setter
        public Builder priority(@Nullable Double priority) {

            this.priority = priority;
            return this;
        }
        @CustomType.Setter
        public Builder target(@Nullable String target) {

            this.target = target;
            return this;
        }
        @CustomType.Setter
        public Builder weight(@Nullable Double weight) {

            this.weight = weight;
            return this;
        }
        public GetSrvRecordSetSrv build() {
            final var _resultValue = new GetSrvRecordSetSrv();
            _resultValue.port = port;
            _resultValue.priority = priority;
            _resultValue.target = target;
            _resultValue.weight = weight;
            return _resultValue;
        }
    }
}
