// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.dns.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetTxtRecordSetResult {
    private String host;
    private String id;
    private String record;
    private List<String> records;

    private GetTxtRecordSetResult() {}
    public String host() {
        return this.host;
    }
    public String id() {
        return this.id;
    }
    public String record() {
        return this.record;
    }
    public List<String> records() {
        return this.records;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetTxtRecordSetResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String host;
        private String id;
        private String record;
        private List<String> records;
        public Builder() {}
        public Builder(GetTxtRecordSetResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.host = defaults.host;
    	      this.id = defaults.id;
    	      this.record = defaults.record;
    	      this.records = defaults.records;
        }

        @CustomType.Setter
        public Builder host(String host) {
            if (host == null) {
              throw new MissingRequiredPropertyException("GetTxtRecordSetResult", "host");
            }
            this.host = host;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetTxtRecordSetResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder record(String record) {
            if (record == null) {
              throw new MissingRequiredPropertyException("GetTxtRecordSetResult", "record");
            }
            this.record = record;
            return this;
        }
        @CustomType.Setter
        public Builder records(List<String> records) {
            if (records == null) {
              throw new MissingRequiredPropertyException("GetTxtRecordSetResult", "records");
            }
            this.records = records;
            return this;
        }
        public Builder records(String... records) {
            return records(List.of(records));
        }
        public GetTxtRecordSetResult build() {
            final var _resultValue = new GetTxtRecordSetResult();
            _resultValue.host = host;
            _resultValue.id = id;
            _resultValue.record = record;
            _resultValue.records = records;
            return _resultValue;
        }
    }
}
