// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.dns.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Double;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class MxRecordSetMx {
    /**
     * @return The FQDN of the mail exchange, include the trailing dot.
     * 
     */
    private String exchange;
    /**
     * @return The preference for the record.
     * 
     */
    private Double preference;

    private MxRecordSetMx() {}
    /**
     * @return The FQDN of the mail exchange, include the trailing dot.
     * 
     */
    public String exchange() {
        return this.exchange;
    }
    /**
     * @return The preference for the record.
     * 
     */
    public Double preference() {
        return this.preference;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(MxRecordSetMx defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String exchange;
        private Double preference;
        public Builder() {}
        public Builder(MxRecordSetMx defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.exchange = defaults.exchange;
    	      this.preference = defaults.preference;
        }

        @CustomType.Setter
        public Builder exchange(String exchange) {
            if (exchange == null) {
              throw new MissingRequiredPropertyException("MxRecordSetMx", "exchange");
            }
            this.exchange = exchange;
            return this;
        }
        @CustomType.Setter
        public Builder preference(Double preference) {
            if (preference == null) {
              throw new MissingRequiredPropertyException("MxRecordSetMx", "preference");
            }
            this.preference = preference;
            return this;
        }
        public MxRecordSetMx build() {
            final var _resultValue = new MxRecordSetMx();
            _resultValue.exchange = exchange;
            _resultValue.preference = preference;
            return _resultValue;
        }
    }
}
