// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.dns.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Double;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class SrvRecordSetSrv {
    /**
     * @return The port for the service on the target.
     * 
     */
    private Double port;
    /**
     * @return The priority for the record.
     * 
     */
    private Double priority;
    /**
     * @return The FQDN of the target, include the trailing dot.
     * 
     */
    private String target;
    /**
     * @return The weight for the record.
     * 
     */
    private Double weight;

    private SrvRecordSetSrv() {}
    /**
     * @return The port for the service on the target.
     * 
     */
    public Double port() {
        return this.port;
    }
    /**
     * @return The priority for the record.
     * 
     */
    public Double priority() {
        return this.priority;
    }
    /**
     * @return The FQDN of the target, include the trailing dot.
     * 
     */
    public String target() {
        return this.target;
    }
    /**
     * @return The weight for the record.
     * 
     */
    public Double weight() {
        return this.weight;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(SrvRecordSetSrv defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private Double port;
        private Double priority;
        private String target;
        private Double weight;
        public Builder() {}
        public Builder(SrvRecordSetSrv defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.port = defaults.port;
    	      this.priority = defaults.priority;
    	      this.target = defaults.target;
    	      this.weight = defaults.weight;
        }

        @CustomType.Setter
        public Builder port(Double port) {
            if (port == null) {
              throw new MissingRequiredPropertyException("SrvRecordSetSrv", "port");
            }
            this.port = port;
            return this;
        }
        @CustomType.Setter
        public Builder priority(Double priority) {
            if (priority == null) {
              throw new MissingRequiredPropertyException("SrvRecordSetSrv", "priority");
            }
            this.priority = priority;
            return this;
        }
        @CustomType.Setter
        public Builder target(String target) {
            if (target == null) {
              throw new MissingRequiredPropertyException("SrvRecordSetSrv", "target");
            }
            this.target = target;
            return this;
        }
        @CustomType.Setter
        public Builder weight(Double weight) {
            if (weight == null) {
              throw new MissingRequiredPropertyException("SrvRecordSetSrv", "weight");
            }
            this.weight = weight;
            return this;
        }
        public SrvRecordSetSrv build() {
            final var _resultValue = new SrvRecordSetSrv();
            _resultValue.port = port;
            _resultValue.priority = priority;
            _resultValue.target = target;
            _resultValue.weight = weight;
            return _resultValue;
        }
    }
}
