// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.dns.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Double;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class CnameRecordState extends com.pulumi.resources.ResourceArgs {

    public static final CnameRecordState Empty = new CnameRecordState();

    /**
     * The canonical name this record will point to.
     * 
     */
    @Import(name="cname")
    private @Nullable Output<String> cname;

    /**
     * @return The canonical name this record will point to.
     * 
     */
    public Optional<Output<String>> cname() {
        return Optional.ofNullable(this.cname);
    }

    /**
     * The name of the record. The &lt;span pulumi-lang-nodejs=&#34;`zone`&#34; pulumi-lang-dotnet=&#34;`Zone`&#34; pulumi-lang-go=&#34;`zone`&#34; pulumi-lang-python=&#34;`zone`&#34; pulumi-lang-yaml=&#34;`zone`&#34; pulumi-lang-java=&#34;`zone`&#34; pulumi-lang-hcl=&#34;`zone`&#34;&gt;`zone`&lt;/span&gt; argument will be appended to this value to create the full record path.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return The name of the record. The &lt;span pulumi-lang-nodejs=&#34;`zone`&#34; pulumi-lang-dotnet=&#34;`Zone`&#34; pulumi-lang-go=&#34;`zone`&#34; pulumi-lang-python=&#34;`zone`&#34; pulumi-lang-yaml=&#34;`zone`&#34; pulumi-lang-java=&#34;`zone`&#34; pulumi-lang-hcl=&#34;`zone`&#34;&gt;`zone`&lt;/span&gt; argument will be appended to this value to create the full record path.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * The TTL of the record set. Defaults to &lt;span pulumi-lang-nodejs=&#34;`3600`&#34; pulumi-lang-dotnet=&#34;`3600`&#34; pulumi-lang-go=&#34;`3600`&#34; pulumi-lang-python=&#34;`3600`&#34; pulumi-lang-yaml=&#34;`3600`&#34; pulumi-lang-java=&#34;`3600`&#34; pulumi-lang-hcl=&#34;`3600`&#34;&gt;`3600`&lt;/span&gt;.
     * 
     */
    @Import(name="ttl")
    private @Nullable Output<Double> ttl;

    /**
     * @return The TTL of the record set. Defaults to &lt;span pulumi-lang-nodejs=&#34;`3600`&#34; pulumi-lang-dotnet=&#34;`3600`&#34; pulumi-lang-go=&#34;`3600`&#34; pulumi-lang-python=&#34;`3600`&#34; pulumi-lang-yaml=&#34;`3600`&#34; pulumi-lang-java=&#34;`3600`&#34; pulumi-lang-hcl=&#34;`3600`&#34;&gt;`3600`&lt;/span&gt;.
     * 
     */
    public Optional<Output<Double>> ttl() {
        return Optional.ofNullable(this.ttl);
    }

    /**
     * DNS zone the record belongs to. It must be an FQDN, that is, include the trailing dot.
     * 
     */
    @Import(name="zone")
    private @Nullable Output<String> zone;

    /**
     * @return DNS zone the record belongs to. It must be an FQDN, that is, include the trailing dot.
     * 
     */
    public Optional<Output<String>> zone() {
        return Optional.ofNullable(this.zone);
    }

    private CnameRecordState() {}

    private CnameRecordState(CnameRecordState $) {
        this.cname = $.cname;
        this.name = $.name;
        this.ttl = $.ttl;
        this.zone = $.zone;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(CnameRecordState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private CnameRecordState $;

        public Builder() {
            $ = new CnameRecordState();
        }

        public Builder(CnameRecordState defaults) {
            $ = new CnameRecordState(Objects.requireNonNull(defaults));
        }

        /**
         * @param cname The canonical name this record will point to.
         * 
         * @return builder
         * 
         */
        public Builder cname(@Nullable Output<String> cname) {
            $.cname = cname;
            return this;
        }

        /**
         * @param cname The canonical name this record will point to.
         * 
         * @return builder
         * 
         */
        public Builder cname(String cname) {
            return cname(Output.of(cname));
        }

        /**
         * @param name The name of the record. The &lt;span pulumi-lang-nodejs=&#34;`zone`&#34; pulumi-lang-dotnet=&#34;`Zone`&#34; pulumi-lang-go=&#34;`zone`&#34; pulumi-lang-python=&#34;`zone`&#34; pulumi-lang-yaml=&#34;`zone`&#34; pulumi-lang-java=&#34;`zone`&#34; pulumi-lang-hcl=&#34;`zone`&#34;&gt;`zone`&lt;/span&gt; argument will be appended to this value to create the full record path.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name The name of the record. The &lt;span pulumi-lang-nodejs=&#34;`zone`&#34; pulumi-lang-dotnet=&#34;`Zone`&#34; pulumi-lang-go=&#34;`zone`&#34; pulumi-lang-python=&#34;`zone`&#34; pulumi-lang-yaml=&#34;`zone`&#34; pulumi-lang-java=&#34;`zone`&#34; pulumi-lang-hcl=&#34;`zone`&#34;&gt;`zone`&lt;/span&gt; argument will be appended to this value to create the full record path.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param ttl The TTL of the record set. Defaults to &lt;span pulumi-lang-nodejs=&#34;`3600`&#34; pulumi-lang-dotnet=&#34;`3600`&#34; pulumi-lang-go=&#34;`3600`&#34; pulumi-lang-python=&#34;`3600`&#34; pulumi-lang-yaml=&#34;`3600`&#34; pulumi-lang-java=&#34;`3600`&#34; pulumi-lang-hcl=&#34;`3600`&#34;&gt;`3600`&lt;/span&gt;.
         * 
         * @return builder
         * 
         */
        public Builder ttl(@Nullable Output<Double> ttl) {
            $.ttl = ttl;
            return this;
        }

        /**
         * @param ttl The TTL of the record set. Defaults to &lt;span pulumi-lang-nodejs=&#34;`3600`&#34; pulumi-lang-dotnet=&#34;`3600`&#34; pulumi-lang-go=&#34;`3600`&#34; pulumi-lang-python=&#34;`3600`&#34; pulumi-lang-yaml=&#34;`3600`&#34; pulumi-lang-java=&#34;`3600`&#34; pulumi-lang-hcl=&#34;`3600`&#34;&gt;`3600`&lt;/span&gt;.
         * 
         * @return builder
         * 
         */
        public Builder ttl(Double ttl) {
            return ttl(Output.of(ttl));
        }

        /**
         * @param zone DNS zone the record belongs to. It must be an FQDN, that is, include the trailing dot.
         * 
         * @return builder
         * 
         */
        public Builder zone(@Nullable Output<String> zone) {
            $.zone = zone;
            return this;
        }

        /**
         * @param zone DNS zone the record belongs to. It must be an FQDN, that is, include the trailing dot.
         * 
         * @return builder
         * 
         */
        public Builder zone(String zone) {
            return zone(Output.of(zone));
        }

        public CnameRecordState build() {
            return $;
        }
    }

}
