// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.dns.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetARecordSetPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetARecordSetPlainArgs Empty = new GetARecordSetPlainArgs();

    @Import(name="host", required=true)
    private String host;

    public String host() {
        return this.host;
    }

    private GetARecordSetPlainArgs() {}

    private GetARecordSetPlainArgs(GetARecordSetPlainArgs $) {
        this.host = $.host;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetARecordSetPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetARecordSetPlainArgs $;

        public Builder() {
            $ = new GetARecordSetPlainArgs();
        }

        public Builder(GetARecordSetPlainArgs defaults) {
            $ = new GetARecordSetPlainArgs(Objects.requireNonNull(defaults));
        }

        public Builder host(String host) {
            $.host = host;
            return this;
        }

        public GetARecordSetPlainArgs build() {
            if ($.host == null) {
                throw new MissingRequiredPropertyException("GetARecordSetPlainArgs", "host");
            }
            return $;
        }
    }

}
