// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.dns.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetAaaaRecordSetPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetAaaaRecordSetPlainArgs Empty = new GetAaaaRecordSetPlainArgs();

    @Import(name="host", required=true)
    private String host;

    public String host() {
        return this.host;
    }

    private GetAaaaRecordSetPlainArgs() {}

    private GetAaaaRecordSetPlainArgs(GetAaaaRecordSetPlainArgs $) {
        this.host = $.host;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetAaaaRecordSetPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetAaaaRecordSetPlainArgs $;

        public Builder() {
            $ = new GetAaaaRecordSetPlainArgs();
        }

        public Builder(GetAaaaRecordSetPlainArgs defaults) {
            $ = new GetAaaaRecordSetPlainArgs(Objects.requireNonNull(defaults));
        }

        public Builder host(String host) {
            $.host = host;
            return this;
        }

        public GetAaaaRecordSetPlainArgs build() {
            if ($.host == null) {
                throw new MissingRequiredPropertyException("GetAaaaRecordSetPlainArgs", "host");
            }
            return $;
        }
    }

}
