// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.dns.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetARecordSetArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetARecordSetArgs Empty = new GetARecordSetArgs();

    @Import(name="host", required=true)
    private Output<String> host;

    public Output<String> host() {
        return this.host;
    }

    private GetARecordSetArgs() {}

    private GetARecordSetArgs(GetARecordSetArgs $) {
        this.host = $.host;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetARecordSetArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetARecordSetArgs $;

        public Builder() {
            $ = new GetARecordSetArgs();
        }

        public Builder(GetARecordSetArgs defaults) {
            $ = new GetARecordSetArgs(Objects.requireNonNull(defaults));
        }

        public Builder host(Output<String> host) {
            $.host = host;
            return this;
        }

        public Builder host(String host) {
            return host(Output.of(host));
        }

        public GetARecordSetArgs build() {
            if ($.host == null) {
                throw new MissingRequiredPropertyException("GetARecordSetArgs", "host");
            }
            return $;
        }
    }

}
