// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.dns.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetCnameRecordSetArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetCnameRecordSetArgs Empty = new GetCnameRecordSetArgs();

    @Import(name="host", required=true)
    private Output<String> host;

    public Output<String> host() {
        return this.host;
    }

    private GetCnameRecordSetArgs() {}

    private GetCnameRecordSetArgs(GetCnameRecordSetArgs $) {
        this.host = $.host;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetCnameRecordSetArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetCnameRecordSetArgs $;

        public Builder() {
            $ = new GetCnameRecordSetArgs();
        }

        public Builder(GetCnameRecordSetArgs defaults) {
            $ = new GetCnameRecordSetArgs(Objects.requireNonNull(defaults));
        }

        public Builder host(Output<String> host) {
            $.host = host;
            return this;
        }

        public Builder host(String host) {
            return host(Output.of(host));
        }

        public GetCnameRecordSetArgs build() {
            if ($.host == null) {
                throw new MissingRequiredPropertyException("GetCnameRecordSetArgs", "host");
            }
            return $;
        }
    }

}
