// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.dns.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetCnameRecordSetPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetCnameRecordSetPlainArgs Empty = new GetCnameRecordSetPlainArgs();

    @Import(name="host", required=true)
    private String host;

    public String host() {
        return this.host;
    }

    private GetCnameRecordSetPlainArgs() {}

    private GetCnameRecordSetPlainArgs(GetCnameRecordSetPlainArgs $) {
        this.host = $.host;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetCnameRecordSetPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetCnameRecordSetPlainArgs $;

        public Builder() {
            $ = new GetCnameRecordSetPlainArgs();
        }

        public Builder(GetCnameRecordSetPlainArgs defaults) {
            $ = new GetCnameRecordSetPlainArgs(Objects.requireNonNull(defaults));
        }

        public Builder host(String host) {
            $.host = host;
            return this;
        }

        public GetCnameRecordSetPlainArgs build() {
            if ($.host == null) {
                throw new MissingRequiredPropertyException("GetCnameRecordSetPlainArgs", "host");
            }
            return $;
        }
    }

}
