// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.dns.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetMxRecordSetArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetMxRecordSetArgs Empty = new GetMxRecordSetArgs();

    @Import(name="domain", required=true)
    private Output<String> domain;

    public Output<String> domain() {
        return this.domain;
    }

    private GetMxRecordSetArgs() {}

    private GetMxRecordSetArgs(GetMxRecordSetArgs $) {
        this.domain = $.domain;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetMxRecordSetArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetMxRecordSetArgs $;

        public Builder() {
            $ = new GetMxRecordSetArgs();
        }

        public Builder(GetMxRecordSetArgs defaults) {
            $ = new GetMxRecordSetArgs(Objects.requireNonNull(defaults));
        }

        public Builder domain(Output<String> domain) {
            $.domain = domain;
            return this;
        }

        public Builder domain(String domain) {
            return domain(Output.of(domain));
        }

        public GetMxRecordSetArgs build() {
            if ($.domain == null) {
                throw new MissingRequiredPropertyException("GetMxRecordSetArgs", "domain");
            }
            return $;
        }
    }

}
