// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.dns.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetMxRecordSetPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetMxRecordSetPlainArgs Empty = new GetMxRecordSetPlainArgs();

    @Import(name="domain", required=true)
    private String domain;

    public String domain() {
        return this.domain;
    }

    private GetMxRecordSetPlainArgs() {}

    private GetMxRecordSetPlainArgs(GetMxRecordSetPlainArgs $) {
        this.domain = $.domain;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetMxRecordSetPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetMxRecordSetPlainArgs $;

        public Builder() {
            $ = new GetMxRecordSetPlainArgs();
        }

        public Builder(GetMxRecordSetPlainArgs defaults) {
            $ = new GetMxRecordSetPlainArgs(Objects.requireNonNull(defaults));
        }

        public Builder domain(String domain) {
            $.domain = domain;
            return this;
        }

        public GetMxRecordSetPlainArgs build() {
            if ($.domain == null) {
                throw new MissingRequiredPropertyException("GetMxRecordSetPlainArgs", "domain");
            }
            return $;
        }
    }

}
