// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.dns.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetNsRecordSetPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetNsRecordSetPlainArgs Empty = new GetNsRecordSetPlainArgs();

    @Import(name="host", required=true)
    private String host;

    public String host() {
        return this.host;
    }

    private GetNsRecordSetPlainArgs() {}

    private GetNsRecordSetPlainArgs(GetNsRecordSetPlainArgs $) {
        this.host = $.host;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetNsRecordSetPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetNsRecordSetPlainArgs $;

        public Builder() {
            $ = new GetNsRecordSetPlainArgs();
        }

        public Builder(GetNsRecordSetPlainArgs defaults) {
            $ = new GetNsRecordSetPlainArgs(Objects.requireNonNull(defaults));
        }

        public Builder host(String host) {
            $.host = host;
            return this;
        }

        public GetNsRecordSetPlainArgs build() {
            if ($.host == null) {
                throw new MissingRequiredPropertyException("GetNsRecordSetPlainArgs", "host");
            }
            return $;
        }
    }

}
