// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.dns.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetPtrRecordSetArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetPtrRecordSetArgs Empty = new GetPtrRecordSetArgs();

    @Import(name="ipAddress", required=true)
    private Output<String> ipAddress;

    public Output<String> ipAddress() {
        return this.ipAddress;
    }

    private GetPtrRecordSetArgs() {}

    private GetPtrRecordSetArgs(GetPtrRecordSetArgs $) {
        this.ipAddress = $.ipAddress;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetPtrRecordSetArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetPtrRecordSetArgs $;

        public Builder() {
            $ = new GetPtrRecordSetArgs();
        }

        public Builder(GetPtrRecordSetArgs defaults) {
            $ = new GetPtrRecordSetArgs(Objects.requireNonNull(defaults));
        }

        public Builder ipAddress(Output<String> ipAddress) {
            $.ipAddress = ipAddress;
            return this;
        }

        public Builder ipAddress(String ipAddress) {
            return ipAddress(Output.of(ipAddress));
        }

        public GetPtrRecordSetArgs build() {
            if ($.ipAddress == null) {
                throw new MissingRequiredPropertyException("GetPtrRecordSetArgs", "ipAddress");
            }
            return $;
        }
    }

}
