// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.dns.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetPtrRecordSetPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetPtrRecordSetPlainArgs Empty = new GetPtrRecordSetPlainArgs();

    @Import(name="ipAddress", required=true)
    private String ipAddress;

    public String ipAddress() {
        return this.ipAddress;
    }

    private GetPtrRecordSetPlainArgs() {}

    private GetPtrRecordSetPlainArgs(GetPtrRecordSetPlainArgs $) {
        this.ipAddress = $.ipAddress;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetPtrRecordSetPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetPtrRecordSetPlainArgs $;

        public Builder() {
            $ = new GetPtrRecordSetPlainArgs();
        }

        public Builder(GetPtrRecordSetPlainArgs defaults) {
            $ = new GetPtrRecordSetPlainArgs(Objects.requireNonNull(defaults));
        }

        public Builder ipAddress(String ipAddress) {
            $.ipAddress = ipAddress;
            return this;
        }

        public GetPtrRecordSetPlainArgs build() {
            if ($.ipAddress == null) {
                throw new MissingRequiredPropertyException("GetPtrRecordSetPlainArgs", "ipAddress");
            }
            return $;
        }
    }

}
