// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.dns.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetSrvRecordSetArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetSrvRecordSetArgs Empty = new GetSrvRecordSetArgs();

    @Import(name="service", required=true)
    private Output<String> service;

    public Output<String> service() {
        return this.service;
    }

    private GetSrvRecordSetArgs() {}

    private GetSrvRecordSetArgs(GetSrvRecordSetArgs $) {
        this.service = $.service;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetSrvRecordSetArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetSrvRecordSetArgs $;

        public Builder() {
            $ = new GetSrvRecordSetArgs();
        }

        public Builder(GetSrvRecordSetArgs defaults) {
            $ = new GetSrvRecordSetArgs(Objects.requireNonNull(defaults));
        }

        public Builder service(Output<String> service) {
            $.service = service;
            return this;
        }

        public Builder service(String service) {
            return service(Output.of(service));
        }

        public GetSrvRecordSetArgs build() {
            if ($.service == null) {
                throw new MissingRequiredPropertyException("GetSrvRecordSetArgs", "service");
            }
            return $;
        }
    }

}
