// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.dns.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetSrvRecordSetPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetSrvRecordSetPlainArgs Empty = new GetSrvRecordSetPlainArgs();

    @Import(name="service", required=true)
    private String service;

    public String service() {
        return this.service;
    }

    private GetSrvRecordSetPlainArgs() {}

    private GetSrvRecordSetPlainArgs(GetSrvRecordSetPlainArgs $) {
        this.service = $.service;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetSrvRecordSetPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetSrvRecordSetPlainArgs $;

        public Builder() {
            $ = new GetSrvRecordSetPlainArgs();
        }

        public Builder(GetSrvRecordSetPlainArgs defaults) {
            $ = new GetSrvRecordSetPlainArgs(Objects.requireNonNull(defaults));
        }

        public Builder service(String service) {
            $.service = service;
            return this;
        }

        public GetSrvRecordSetPlainArgs build() {
            if ($.service == null) {
                throw new MissingRequiredPropertyException("GetSrvRecordSetPlainArgs", "service");
            }
            return $;
        }
    }

}
