// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.dns.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetTxtRecordSetArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetTxtRecordSetArgs Empty = new GetTxtRecordSetArgs();

    @Import(name="host", required=true)
    private Output<String> host;

    public Output<String> host() {
        return this.host;
    }

    private GetTxtRecordSetArgs() {}

    private GetTxtRecordSetArgs(GetTxtRecordSetArgs $) {
        this.host = $.host;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetTxtRecordSetArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetTxtRecordSetArgs $;

        public Builder() {
            $ = new GetTxtRecordSetArgs();
        }

        public Builder(GetTxtRecordSetArgs defaults) {
            $ = new GetTxtRecordSetArgs(Objects.requireNonNull(defaults));
        }

        public Builder host(Output<String> host) {
            $.host = host;
            return this;
        }

        public Builder host(String host) {
            return host(Output.of(host));
        }

        public GetTxtRecordSetArgs build() {
            if ($.host == null) {
                throw new MissingRequiredPropertyException("GetTxtRecordSetArgs", "host");
            }
            return $;
        }
    }

}
