// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.dns.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetTxtRecordSetPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetTxtRecordSetPlainArgs Empty = new GetTxtRecordSetPlainArgs();

    @Import(name="host", required=true)
    private String host;

    public String host() {
        return this.host;
    }

    private GetTxtRecordSetPlainArgs() {}

    private GetTxtRecordSetPlainArgs(GetTxtRecordSetPlainArgs $) {
        this.host = $.host;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetTxtRecordSetPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetTxtRecordSetPlainArgs $;

        public Builder() {
            $ = new GetTxtRecordSetPlainArgs();
        }

        public Builder(GetTxtRecordSetPlainArgs defaults) {
            $ = new GetTxtRecordSetPlainArgs(Objects.requireNonNull(defaults));
        }

        public Builder host(String host) {
            $.host = host;
            return this;
        }

        public GetTxtRecordSetPlainArgs build() {
            if ($.host == null) {
                throw new MissingRequiredPropertyException("GetTxtRecordSetPlainArgs", "host");
            }
            return $;
        }
    }

}
