// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.dns.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Double;
import java.lang.String;
import java.util.Objects;


public final class MxRecordSetMxArgs extends com.pulumi.resources.ResourceArgs {

    public static final MxRecordSetMxArgs Empty = new MxRecordSetMxArgs();

    /**
     * The FQDN of the mail exchange, include the trailing dot.
     * 
     */
    @Import(name="exchange", required=true)
    private Output<String> exchange;

    /**
     * @return The FQDN of the mail exchange, include the trailing dot.
     * 
     */
    public Output<String> exchange() {
        return this.exchange;
    }

    /**
     * The preference for the record.
     * 
     */
    @Import(name="preference", required=true)
    private Output<Double> preference;

    /**
     * @return The preference for the record.
     * 
     */
    public Output<Double> preference() {
        return this.preference;
    }

    private MxRecordSetMxArgs() {}

    private MxRecordSetMxArgs(MxRecordSetMxArgs $) {
        this.exchange = $.exchange;
        this.preference = $.preference;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(MxRecordSetMxArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private MxRecordSetMxArgs $;

        public Builder() {
            $ = new MxRecordSetMxArgs();
        }

        public Builder(MxRecordSetMxArgs defaults) {
            $ = new MxRecordSetMxArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param exchange The FQDN of the mail exchange, include the trailing dot.
         * 
         * @return builder
         * 
         */
        public Builder exchange(Output<String> exchange) {
            $.exchange = exchange;
            return this;
        }

        /**
         * @param exchange The FQDN of the mail exchange, include the trailing dot.
         * 
         * @return builder
         * 
         */
        public Builder exchange(String exchange) {
            return exchange(Output.of(exchange));
        }

        /**
         * @param preference The preference for the record.
         * 
         * @return builder
         * 
         */
        public Builder preference(Output<Double> preference) {
            $.preference = preference;
            return this;
        }

        /**
         * @param preference The preference for the record.
         * 
         * @return builder
         * 
         */
        public Builder preference(Double preference) {
            return preference(Output.of(preference));
        }

        public MxRecordSetMxArgs build() {
            if ($.exchange == null) {
                throw new MissingRequiredPropertyException("MxRecordSetMxArgs", "exchange");
            }
            if ($.preference == null) {
                throw new MissingRequiredPropertyException("MxRecordSetMxArgs", "preference");
            }
            return $;
        }
    }

}
