// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.dns.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.dns.inputs.SrvRecordSetSrvArgs;
import java.lang.Double;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class SrvRecordSetState extends com.pulumi.resources.ResourceArgs {

    public static final SrvRecordSetState Empty = new SrvRecordSetState();

    /**
     * The name of the record set. The &lt;span pulumi-lang-nodejs=&#34;`zone`&#34; pulumi-lang-dotnet=&#34;`Zone`&#34; pulumi-lang-go=&#34;`zone`&#34; pulumi-lang-python=&#34;`zone`&#34; pulumi-lang-yaml=&#34;`zone`&#34; pulumi-lang-java=&#34;`zone`&#34; pulumi-lang-hcl=&#34;`zone`&#34;&gt;`zone`&lt;/span&gt; argument will be appended to this value to create the full record path.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return The name of the record set. The &lt;span pulumi-lang-nodejs=&#34;`zone`&#34; pulumi-lang-dotnet=&#34;`Zone`&#34; pulumi-lang-go=&#34;`zone`&#34; pulumi-lang-python=&#34;`zone`&#34; pulumi-lang-yaml=&#34;`zone`&#34; pulumi-lang-java=&#34;`zone`&#34; pulumi-lang-hcl=&#34;`zone`&#34;&gt;`zone`&lt;/span&gt; argument will be appended to this value to create the full record path.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * Can be specified multiple times for each SRV record.
     * 
     */
    @Import(name="srvs")
    private @Nullable Output<List<SrvRecordSetSrvArgs>> srvs;

    /**
     * @return Can be specified multiple times for each SRV record.
     * 
     */
    public Optional<Output<List<SrvRecordSetSrvArgs>>> srvs() {
        return Optional.ofNullable(this.srvs);
    }

    /**
     * The TTL of the record set. Defaults to &lt;span pulumi-lang-nodejs=&#34;`3600`&#34; pulumi-lang-dotnet=&#34;`3600`&#34; pulumi-lang-go=&#34;`3600`&#34; pulumi-lang-python=&#34;`3600`&#34; pulumi-lang-yaml=&#34;`3600`&#34; pulumi-lang-java=&#34;`3600`&#34; pulumi-lang-hcl=&#34;`3600`&#34;&gt;`3600`&lt;/span&gt;.
     * 
     */
    @Import(name="ttl")
    private @Nullable Output<Double> ttl;

    /**
     * @return The TTL of the record set. Defaults to &lt;span pulumi-lang-nodejs=&#34;`3600`&#34; pulumi-lang-dotnet=&#34;`3600`&#34; pulumi-lang-go=&#34;`3600`&#34; pulumi-lang-python=&#34;`3600`&#34; pulumi-lang-yaml=&#34;`3600`&#34; pulumi-lang-java=&#34;`3600`&#34; pulumi-lang-hcl=&#34;`3600`&#34;&gt;`3600`&lt;/span&gt;.
     * 
     */
    public Optional<Output<Double>> ttl() {
        return Optional.ofNullable(this.ttl);
    }

    /**
     * DNS zone the record set belongs to. It must be an FQDN, that is, include the trailing dot.
     * 
     */
    @Import(name="zone")
    private @Nullable Output<String> zone;

    /**
     * @return DNS zone the record set belongs to. It must be an FQDN, that is, include the trailing dot.
     * 
     */
    public Optional<Output<String>> zone() {
        return Optional.ofNullable(this.zone);
    }

    private SrvRecordSetState() {}

    private SrvRecordSetState(SrvRecordSetState $) {
        this.name = $.name;
        this.srvs = $.srvs;
        this.ttl = $.ttl;
        this.zone = $.zone;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SrvRecordSetState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SrvRecordSetState $;

        public Builder() {
            $ = new SrvRecordSetState();
        }

        public Builder(SrvRecordSetState defaults) {
            $ = new SrvRecordSetState(Objects.requireNonNull(defaults));
        }

        /**
         * @param name The name of the record set. The &lt;span pulumi-lang-nodejs=&#34;`zone`&#34; pulumi-lang-dotnet=&#34;`Zone`&#34; pulumi-lang-go=&#34;`zone`&#34; pulumi-lang-python=&#34;`zone`&#34; pulumi-lang-yaml=&#34;`zone`&#34; pulumi-lang-java=&#34;`zone`&#34; pulumi-lang-hcl=&#34;`zone`&#34;&gt;`zone`&lt;/span&gt; argument will be appended to this value to create the full record path.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name The name of the record set. The &lt;span pulumi-lang-nodejs=&#34;`zone`&#34; pulumi-lang-dotnet=&#34;`Zone`&#34; pulumi-lang-go=&#34;`zone`&#34; pulumi-lang-python=&#34;`zone`&#34; pulumi-lang-yaml=&#34;`zone`&#34; pulumi-lang-java=&#34;`zone`&#34; pulumi-lang-hcl=&#34;`zone`&#34;&gt;`zone`&lt;/span&gt; argument will be appended to this value to create the full record path.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param srvs Can be specified multiple times for each SRV record.
         * 
         * @return builder
         * 
         */
        public Builder srvs(@Nullable Output<List<SrvRecordSetSrvArgs>> srvs) {
            $.srvs = srvs;
            return this;
        }

        /**
         * @param srvs Can be specified multiple times for each SRV record.
         * 
         * @return builder
         * 
         */
        public Builder srvs(List<SrvRecordSetSrvArgs> srvs) {
            return srvs(Output.of(srvs));
        }

        /**
         * @param srvs Can be specified multiple times for each SRV record.
         * 
         * @return builder
         * 
         */
        public Builder srvs(SrvRecordSetSrvArgs... srvs) {
            return srvs(List.of(srvs));
        }

        /**
         * @param ttl The TTL of the record set. Defaults to &lt;span pulumi-lang-nodejs=&#34;`3600`&#34; pulumi-lang-dotnet=&#34;`3600`&#34; pulumi-lang-go=&#34;`3600`&#34; pulumi-lang-python=&#34;`3600`&#34; pulumi-lang-yaml=&#34;`3600`&#34; pulumi-lang-java=&#34;`3600`&#34; pulumi-lang-hcl=&#34;`3600`&#34;&gt;`3600`&lt;/span&gt;.
         * 
         * @return builder
         * 
         */
        public Builder ttl(@Nullable Output<Double> ttl) {
            $.ttl = ttl;
            return this;
        }

        /**
         * @param ttl The TTL of the record set. Defaults to &lt;span pulumi-lang-nodejs=&#34;`3600`&#34; pulumi-lang-dotnet=&#34;`3600`&#34; pulumi-lang-go=&#34;`3600`&#34; pulumi-lang-python=&#34;`3600`&#34; pulumi-lang-yaml=&#34;`3600`&#34; pulumi-lang-java=&#34;`3600`&#34; pulumi-lang-hcl=&#34;`3600`&#34;&gt;`3600`&lt;/span&gt;.
         * 
         * @return builder
         * 
         */
        public Builder ttl(Double ttl) {
            return ttl(Output.of(ttl));
        }

        /**
         * @param zone DNS zone the record set belongs to. It must be an FQDN, that is, include the trailing dot.
         * 
         * @return builder
         * 
         */
        public Builder zone(@Nullable Output<String> zone) {
            $.zone = zone;
            return this;
        }

        /**
         * @param zone DNS zone the record set belongs to. It must be an FQDN, that is, include the trailing dot.
         * 
         * @return builder
         * 
         */
        public Builder zone(String zone) {
            return zone(Output.of(zone));
        }

        public SrvRecordSetState build() {
            return $;
        }
    }

}
