// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.dns.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Double;
import java.lang.String;
import java.util.Objects;


public final class SrvRecordSetSrvArgs extends com.pulumi.resources.ResourceArgs {

    public static final SrvRecordSetSrvArgs Empty = new SrvRecordSetSrvArgs();

    /**
     * The port for the service on the target.
     * 
     */
    @Import(name="port", required=true)
    private Output<Double> port;

    /**
     * @return The port for the service on the target.
     * 
     */
    public Output<Double> port() {
        return this.port;
    }

    /**
     * The priority for the record.
     * 
     */
    @Import(name="priority", required=true)
    private Output<Double> priority;

    /**
     * @return The priority for the record.
     * 
     */
    public Output<Double> priority() {
        return this.priority;
    }

    /**
     * The FQDN of the target, include the trailing dot.
     * 
     */
    @Import(name="target", required=true)
    private Output<String> target;

    /**
     * @return The FQDN of the target, include the trailing dot.
     * 
     */
    public Output<String> target() {
        return this.target;
    }

    /**
     * The weight for the record.
     * 
     */
    @Import(name="weight", required=true)
    private Output<Double> weight;

    /**
     * @return The weight for the record.
     * 
     */
    public Output<Double> weight() {
        return this.weight;
    }

    private SrvRecordSetSrvArgs() {}

    private SrvRecordSetSrvArgs(SrvRecordSetSrvArgs $) {
        this.port = $.port;
        this.priority = $.priority;
        this.target = $.target;
        this.weight = $.weight;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SrvRecordSetSrvArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SrvRecordSetSrvArgs $;

        public Builder() {
            $ = new SrvRecordSetSrvArgs();
        }

        public Builder(SrvRecordSetSrvArgs defaults) {
            $ = new SrvRecordSetSrvArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param port The port for the service on the target.
         * 
         * @return builder
         * 
         */
        public Builder port(Output<Double> port) {
            $.port = port;
            return this;
        }

        /**
         * @param port The port for the service on the target.
         * 
         * @return builder
         * 
         */
        public Builder port(Double port) {
            return port(Output.of(port));
        }

        /**
         * @param priority The priority for the record.
         * 
         * @return builder
         * 
         */
        public Builder priority(Output<Double> priority) {
            $.priority = priority;
            return this;
        }

        /**
         * @param priority The priority for the record.
         * 
         * @return builder
         * 
         */
        public Builder priority(Double priority) {
            return priority(Output.of(priority));
        }

        /**
         * @param target The FQDN of the target, include the trailing dot.
         * 
         * @return builder
         * 
         */
        public Builder target(Output<String> target) {
            $.target = target;
            return this;
        }

        /**
         * @param target The FQDN of the target, include the trailing dot.
         * 
         * @return builder
         * 
         */
        public Builder target(String target) {
            return target(Output.of(target));
        }

        /**
         * @param weight The weight for the record.
         * 
         * @return builder
         * 
         */
        public Builder weight(Output<Double> weight) {
            $.weight = weight;
            return this;
        }

        /**
         * @param weight The weight for the record.
         * 
         * @return builder
         * 
         */
        public Builder weight(Double weight) {
            return weight(Output.of(weight));
        }

        public SrvRecordSetSrvArgs build() {
            if ($.port == null) {
                throw new MissingRequiredPropertyException("SrvRecordSetSrvArgs", "port");
            }
            if ($.priority == null) {
                throw new MissingRequiredPropertyException("SrvRecordSetSrvArgs", "priority");
            }
            if ($.target == null) {
                throw new MissingRequiredPropertyException("SrvRecordSetSrvArgs", "target");
            }
            if ($.weight == null) {
                throw new MissingRequiredPropertyException("SrvRecordSetSrvArgs", "weight");
            }
            return $;
        }
    }

}
